SELECT
    A.POSITION_NBR,
    A.DESCR AS POSN_DESCR,
    A.DEPTID,
    A.DEPTID_DESCR,
    A.JOBCODE,
    A.JOBCODE_DESCR,
    A.FTE,
    A.REPORTS_TO,
    G.ACCOUNT,
    G.DEPTID_CF,
    D.DESCR AS DEPTID_CF_DESCR,
    G.FUND_CODE,
    G.OPERATING_UNIT,
    G.ACCT_CD AS FDM_COMBO_CD, --
    f.ERNCD, f.FISCAL_YEAR,
    F.DIST_PCT , --	f.erncd, F.ACCT_CD,	 -- CASE WHEN F.EARNCD = 'REG' THEN 'ZZZ'  WHEN F.EARNCD = '' THEN 'ZZY' ELSE F.EARNCD END AS TEST, 
    G.PROJECT_ID,
    G.PRODUCT,
    G.CHARTFIELD1,
    G.CHARTFIELD2,
    G.CHARTFIELD3,
    G.PROGRAM_CODE,
    G.CLASS_FLD,
    -- G.FDM_HASH,
    ROW_NUMBER() OVER (PARTITION BY A.POSITION_NBR ORDER BY (CASE WHEN F.ERNCD = 'REG' THEN 'ZZZ'  WHEN F.ERNCD = '' THEN 'ZZY' ELSE F.ERNCD END ) DESC, DIST_PCT DESC , G.ACCT_CD ) AS POSN_SEQ
-- seq by ERNCD 'REG','' and others.
FROM [RPT].[CURRENT_POSITION] A
    LEFT OUTER JOIN STABLE.PS_DEPT_BUDGET_ERN F
    ON A.POSITION_NBR = F.POSITION_NBR
        AND A.POSITION_NBR <> ''
        AND F.DML_IND <> 'D'
        AND (F.FUNDING_END_DT >= CURRENT_TIMESTAMP OR F.FUNDING_END_DT  IS NULL)
        AND F.SETID = 'SDCMP'
        AND F.FISCAL_YEAR = YEAR( DATEADD(MONTH, 6, GETDATE()))
        /*
 AND F.FISCAL_YEAR <= YEAR( DATEADD(MONTH, 6, GETDATE()))   
 AND F.FISCAL_YEAR = (SELECT MAX(FF.FISCAL_YEAR) FROM STABLE.PS_DEPT_BUDGET_ERN FF 
	                    WHERE FF.SETID = 'SDCMP' --AND FF.DEPTID = F.DEPTID 
	                    --AND FF.POSITION_NBR = F.POSITION_NBR
					 AND FF.EFFDT < CURRENT_TIMESTAMP
						  AND FF.DML_IND <> 'D' --AND FF.ERNCD = ''
						  ) */
        AND F.EFFDT =
        (SELECT MAX(F_ED.EFFDT)
        FROM STABLE.PS_DEPT_BUDGET_ERN F_ED
        WHERE F.SETID = F_ED.SETID
            AND F.DEPTID = F_ED.DEPTID
            AND F.FISCAL_YEAR = F_ED.FISCAL_YEAR
            AND F.POSITION_POOL_ID = F_ED.POSITION_POOL_ID
            AND F.SETID_JOBCODE = F_ED.SETID_JOBCODE
            AND F.JOBCODE = F_ED.JOBCODE
            AND F.POSITION_NBR = F_ED.POSITION_NBR
            AND F.EMPLID = F_ED.EMPLID
            AND F.EMPL_RCD = F_ED.EMPL_RCD
            AND F_ED.EFFDT <= CURRENT_TIMESTAMP
            AND F_ED.DML_IND <> 'D'		 
		  )
        AND F.EFFSEQ =
        (SELECT MAX(F_ES.EFFSEQ)
        FROM STABLE.PS_DEPT_BUDGET_ERN F_ES
        WHERE F.SETID = F_ES.SETID
            AND F.DEPTID = F_ES.DEPTID
            AND F.FISCAL_YEAR = F_ES.FISCAL_YEAR
            AND F.POSITION_POOL_ID = F_ES.POSITION_POOL_ID
            AND F.SETID_JOBCODE = F_ES.SETID_JOBCODE
            AND F.JOBCODE = F_ES.JOBCODE
            AND F.POSITION_NBR = F_ES.POSITION_NBR
            AND F.EMPLID = F_ES.EMPLID
            AND F.EMPL_RCD = F_ES.EMPL_RCD
            AND F.EFFDT = F_ES.EFFDT
            AND F_ES.DML_IND <> 'D'		 
		  )
        AND F.BUDGET_SEQ = (SELECT MAX(FF.BUDGET_SEQ)
        FROM STABLE.PS_DEPT_BUDGET_ERN FF
        WHERE FF.SETID = F.SETID AND FF.DEPTID = F.DEPTID
            AND FF.FISCAL_YEAR = F.FISCAL_YEAR
            AND FF.POSITION_NBR = F.POSITION_NBR AND FF.EMPLID = F.EMPLID
            AND FF.EMPL_RCD = F.EMPL_RCD AND FF.EFFDT = F.EFFDT
            AND FF.EFFSEQ = F.EFFSEQ
            AND FF.ERNCD = F.ERNCD
            AND FF.DML_IND <> 'D')
    LEFT OUTER JOIN STABLE.PS_ACCT_CD_TBL G
    ON  F.ACCT_CD = G.ACCT_CD --
        AND F.ACCT_CD <> ''
        AND G.DML_IND <> 'D'
    LEFT OUTER JOIN STABLE.PS_DEPT_TBL D
    ON D.DEPTID = G.DEPTID_CF
        AND D.SETID = 'SDFIN'
        AND D.EFFDT =
        (SELECT MAX(D_ED.EFFDT)
        FROM STABLE.PS_DEPT_TBL D_ED
        WHERE D.SETID  = D_ED.SETID
            AND D.DEPTID = D_ED.DEPTID
            --AND D_ED.EFFDT <= G.EFFDT		 --
            AND D_ED.DML_IND <> 'D'
            AND D_ED.EFF_STATUS = 'A')
        AND D.DML_IND <> 'D'
        AND D.EFF_STATUS = 'A'
WHERE  A.POSN_STATUS = 'A'

-- QA Check for POSITION_NBR = '40706162'
DECLARE @POSITION_NBR VARCHAR(20) = '40706162';

PRINT '=== QA CHECK FOR POSITION_NBR: ' + @POSITION_NBR + ' ===';
PRINT '';

-- Step 1: Check if position exists in CURRENT_POSITION
PRINT '1. Checking CURRENT_POSITION table...';
IF EXISTS (SELECT 1
FROM [RPT].[CURRENT_POSITION]
WHERE POSITION_NBR = @POSITION_NBR)
BEGIN
    SELECT
        POSITION_NBR,
        POSN_STATUS,
        DESCR as POSN_DESCR,
        DEPTID,
        JOBCODE,
        FTE,
        REPORTS_TO
    FROM [RPT].[CURRENT_POSITION]
    WHERE POSITION_NBR = @POSITION_NBR;

    -- Check POSN_STATUS filter
    IF EXISTS (SELECT 1
    FROM [RPT].[CURRENT_POSITION]
    WHERE POSITION_NBR = @POSITION_NBR AND POSN_STATUS = 'A')
        PRINT '   ✓ Position exists and POSN_STATUS = ''A''';
    ELSE
        PRINT '   ✗ Position exists but POSN_STATUS <> ''A'' - FILTERED OUT';
END
ELSE
BEGIN
    PRINT '   ✗ Position does not exist in CURRENT_POSITION - FILTERED OUT';
    RETURN;
END

PRINT '';

-- Step 2: Check PS_DEPT_BUDGET_ERN join conditions
PRINT '2. Checking PS_DEPT_BUDGET_ERN join conditions...';
DECLARE @CurrentFiscalYear INT = YEAR(DATEADD(MONTH, 6, GETDATE()));
PRINT '   Current Fiscal Year filter: ' + CAST(@CurrentFiscalYear AS VARCHAR);

-- Check if position has any budget records
IF EXISTS (
    SELECT 1
FROM STABLE.PS_DEPT_BUDGET_ERN
WHERE POSITION_NBR = @POSITION_NBR
    AND DML_IND <> 'D'
    AND (FUNDING_END_DT >= CURRENT_TIMESTAMP OR FUNDING_END_DT IS NULL)
    AND SETID = 'SDCMP'
    AND FISCAL_YEAR = @CurrentFiscalYear
)
BEGIN
    PRINT '   ✓ Position has matching PS_DEPT_BUDGET_ERN records';

    -- Show the budget records that would match
    SELECT TOP 5
        POSITION_NBR,
        FISCAL_YEAR,
        ERNCD,
        DIST_PCT,
        FUNDING_END_DT,
        EFFDT,
        EFFSEQ,
        BUDGET_SEQ,
        ACCT_CD
    FROM STABLE.PS_DEPT_BUDGET_ERN
    WHERE POSITION_NBR = @POSITION_NBR
        AND DML_IND <> 'D'
        AND (FUNDING_END_DT >= CURRENT_TIMESTAMP OR FUNDING_END_DT IS NULL)
        AND SETID = 'SDCMP'
        AND FISCAL_YEAR = @CurrentFiscalYear
    ORDER BY EFFDT DESC, EFFSEQ DESC, BUDGET_SEQ DESC;
END
ELSE
BEGIN
    PRINT '   ✗ No matching PS_DEPT_BUDGET_ERN records found';

    -- Check what budget records exist for this position
    IF EXISTS (SELECT 1
    FROM STABLE.PS_DEPT_BUDGET_ERN
    WHERE POSITION_NBR = @POSITION_NBR)
    BEGIN
        PRINT '   Available budget records for this position:';
        SELECT DISTINCT
            FISCAL_YEAR,
            SETID,
            DML_IND,
            FUNDING_END_DT,
            COUNT(*) as Record_Count
        FROM STABLE.PS_DEPT_BUDGET_ERN
        WHERE POSITION_NBR = @POSITION_NBR
        GROUP BY FISCAL_YEAR, SETID, DML_IND, FUNDING_END_DT
        ORDER BY FISCAL_YEAR DESC;
    END
    ELSE
        PRINT '   No budget records exist for this position at all';
END

PRINT '';

-- Step 3: Check PS_ACCT_CD_TBL join
PRINT '3. Checking PS_ACCT_CD_TBL join...';
SELECT DISTINCT
    F.ACCT_CD,
    G.ACCT_CD as G_ACCT_CD,
    CASE WHEN G.ACCT_CD IS NOT NULL THEN '✓ Match' ELSE '✗ No Match' END as Join_Status,
    G.ACCT_CD AS FDM_COMBO_CD,
    G.FUND_CODE
FROM STABLE.PS_DEPT_BUDGET_ERN F
    LEFT JOIN STABLE.PS_ACCT_CD_TBL G ON F.ACCT_CD = G.ACCT_CD
        AND F.ACCT_CD <> ''
        AND G.DML_IND <> 'D'
WHERE F.POSITION_NBR = @POSITION_NBR
    AND F.DML_IND <> 'D'
    AND (F.FUNDING_END_DT >= CURRENT_TIMESTAMP OR F.FUNDING_END_DT IS NULL)
    AND F.SETID = 'SDCMP'
    AND F.FISCAL_YEAR = @CurrentFiscalYear;

PRINT '';

-- Step 4: Check PS_DEPT_TBL join
PRINT '4. Checking PS_DEPT_TBL join...';
SELECT DISTINCT
    G.DEPTID_CF,
    D.DEPTID as D_DEPTID,
    CASE WHEN D.DEPTID IS NOT NULL THEN '✓ Match' ELSE '✗ No Match' END as Join_Status,
    D.DESCR as DEPT_DESCR
FROM STABLE.PS_DEPT_BUDGET_ERN F
    LEFT JOIN STABLE.PS_ACCT_CD_TBL G ON F.ACCT_CD = G.ACCT_CD
        AND F.ACCT_CD <> ''
        AND G.DML_IND <> 'D'
    LEFT JOIN STABLE.PS_DEPT_TBL D ON D.DEPTID = G.DEPTID_CF
        AND D.SETID = 'SDFIN'
        AND D.DML_IND <> 'D'
        AND D.EFF_STATUS = 'A'
WHERE F.POSITION_NBR = @POSITION_NBR
    AND F.DML_IND <> 'D'
    AND (F.FUNDING_END_DT >= CURRENT_TIMESTAMP OR F.FUNDING_END_DT IS NULL)
    AND F.SETID = 'SDCMP'
    AND F.FISCAL_YEAR = @CurrentFiscalYear;

PRINT '';

-- Step 5: Final result check
PRINT '5. Final query result check...';
DECLARE @ResultCount INT;
SELECT @ResultCount = COUNT(*)
FROM [RPT].[CURRENT_POSITION] A
    LEFT OUTER JOIN STABLE.PS_DEPT_BUDGET_ERN F
    ON A.POSITION_NBR = F.POSITION_NBR
        AND A.POSITION_NBR <> ''
        AND F.DML_IND <> 'D'
        AND (F.FUNDING_END_DT >= CURRENT_TIMESTAMP OR F.FUNDING_END_DT IS NULL)
        AND F.SETID = 'SDCMP'
        AND F.FISCAL_YEAR = YEAR(DATEADD(MONTH, 6, GETDATE()))
        AND F.EFFDT = (SELECT MAX(F_ED.EFFDT)
        FROM STABLE.PS_DEPT_BUDGET_ERN F_ED
        WHERE F.SETID = F_ED.SETID AND F.DEPTID = F_ED.DEPTID AND F.FISCAL_YEAR = F_ED.FISCAL_YEAR
            AND F.POSITION_POOL_ID = F_ED.POSITION_POOL_ID AND F.SETID_JOBCODE = F_ED.SETID_JOBCODE
            AND F.JOBCODE = F_ED.JOBCODE AND F.POSITION_NBR = F_ED.POSITION_NBR
            AND F.EMPLID = F_ED.EMPLID AND F.EMPL_RCD = F_ED.EMPL_RCD
            AND F_ED.EFFDT <= CURRENT_TIMESTAMP AND F_ED.DML_IND <> 'D')
        AND F.EFFSEQ = (SELECT MAX(F_ES.EFFSEQ)
        FROM STABLE.PS_DEPT_BUDGET_ERN F_ES
        WHERE F.SETID = F_ES.SETID AND F.DEPTID = F_ES.DEPTID AND F.FISCAL_YEAR = F_ES.FISCAL_YEAR
            AND F.POSITION_POOL_ID = F_ES.POSITION_POOL_ID AND F.SETID_JOBCODE = F_ES.SETID_JOBCODE
            AND F.JOBCODE = F_ES.JOBCODE AND F.POSITION_NBR = F_ES.POSITION_NBR
            AND F.EMPLID = F_ES.EMPLID AND F.EMPL_RCD = F_ES.EMPL_RCD
            AND F.EFFDT = F_ES.EFFDT AND F_ES.DML_IND <> 'D')
        AND F.BUDGET_SEQ = (SELECT MAX(FF.BUDGET_SEQ)
        FROM STABLE.PS_DEPT_BUDGET_ERN FF
        WHERE FF.SETID = F.SETID AND FF.DEPTID = F.DEPTID AND FF.FISCAL_YEAR = F.FISCAL_YEAR
            AND FF.POSITION_NBR = F.POSITION_NBR AND FF.EMPLID = F.EMPLID AND FF.EMPL_RCD = F.EMPL_RCD
            AND FF.EFFDT = F.EFFDT AND FF.EFFSEQ = F.EFFSEQ AND FF.ERNCD = F.ERNCD AND FF.DML_IND <> 'D')
    LEFT OUTER JOIN STABLE.PS_ACCT_CD_TBL G ON F.ACCT_CD = G.ACCT_CD AND F.ACCT_CD <> '' AND G.DML_IND <> 'D'
    LEFT OUTER JOIN STABLE.PS_DEPT_TBL D ON D.DEPTID = G.DEPTID_CF AND D.SETID = 'SDFIN'
        AND D.EFFDT = (SELECT MAX(D_ED.EFFDT)
        FROM STABLE.PS_DEPT_TBL D_ED
        WHERE D.SETID = D_ED.SETID AND D.DEPTID = D_ED.DEPTID AND D_ED.DML_IND <> 'D' AND D_ED.EFF_STATUS = 'A')
        AND D.DML_IND <> 'D' AND D.EFF_STATUS = 'A'
WHERE A.POSITION_NBR = @POSITION_NBR AND A.POSN_STATUS = 'A';

IF @ResultCount > 0
    PRINT '   ✓ Position appears in final query results (' + CAST(@ResultCount AS VARCHAR) + ' records)';
ELSE
    PRINT '   ✗ Position does NOT appear in final query results - FILTERED OUT';

PRINT '';
PRINT '=== QA CHECK COMPLETE ===';