SELECT
    POSN.POSITION_NBR,
    POSN.EFFDT,
    POSN.EFF_STATUS,
    POSN.DESCR,
    POSN.DESCRSHORT,
    POSN.ACTION,
    POSN.ACTION_REASON,
    POSN.ACTION_DT,
    POSN.BUSINESS_UNIT,
    POSN.DEPTID,
    DEPT_VC.DESCR AS DEPTID_DESCR,
    POSN.JOBCODE,
    H.DESCR AS JOBCODE_DESCR,
    POSN.POSN_STATUS,
    POSN.STATUS_DT,
    POSN.BUDGETED_POSN,
    POSN.CONFIDENTIAL_POSN,
    POSN.JOB_SHARE,
    POSN.KEY_POSITION,
    POSN.MAX_HEAD_COUNT,
    POSN.UPDATE_INCUMBENTS,
    --POSN.REPORTS_TO,
    CASE WHEN POSN.POSITION_NBR = '40697795' THEN  '40786234' 
     ELSE  POSN.REPORTS_TO END AS REPORTS_TO,
    POSN.REPORT_DOTTED_LINE,
    POSN.ORGCODE,
    POSN.ORGCODE_FLAG,
    POSN.LOCATION,
    POSN.MAIL_DROP,
    POSN.COUNTRY_CODE,
    POSN.PHONE,
    POSN.COMPANY,
    POSN.STD_HOURS,
    POSN.STD_HRS_FREQUENCY,
    POSN.UNION_CD,
    POSN.SHIFT,
    POSN.REG_TEMP,
    POSN.FULL_PART_TIME,
    POSN.MON_HRS,
    POSN.TUES_HRS,
    POSN.WED_HRS,
    POSN.THURS_HRS,
    POSN.FRI_HRS,
    POSN.SAT_HRS,
    POSN.SUN_HRS,
    POSN.BARG_UNIT,
    POSN.SEASONAL,
    POSN.TRN_PROGRAM,
    POSN.LANGUAGE_SKILL,
    POSN.MANAGER_LEVEL,
    POSN.FLSA_STATUS,
    POSN.REG_REGION,
    POSN.CLASS_INDC,
    POSN.ENCUMBER_INDC,
    POSN.FTE,
    POSN.POSITION_POOL_ID,
    POSN.EG_ACADEMIC_RANK,
    POSN.EG_GROUP,
    POSN.ENCUMB_SAL_OPTN,
    POSN.ENCUMB_SAL_AMT,
    POSN.HEALTH_CERTIFICATE,
    POSN.SIGN_AUTHORITY,
    POSN.ADDS_TO_FTE_ACTUAL,
    POSN.SAL_ADMIN_PLAN,
    POSN.GRADE,
    POSN.STEP,
    POSN.SUPV_LVL_ID,
    POSN.INCLUDE_SALPLN_FLG,
    POSN.LASTUPDDTTM,
    POSN.LASTUPDOPRID,
    POSN.SEC_CLEARANCE_TYPE,
    POSN.AVAIL_TELEWORK_POS,
    POSN.CR_BT_DTM,
    POSN.CR_BT_NBR,
    POSN.UPD_BT_DTM,
    POSN.UPD_BT_NBR,
    POSN.ODS_VRSN_NBR,
    POSN.DML_IND,
    DEPT_VC.VC_CODE,
    DEPT_VC.VC_NAME
FROM STABLE.PS_POSITION_DATA POSN
    LEFT OUTER JOIN STABLE.PS_JOBCODE_TBL H
    ON H.JOBCODE = POSN.JOBCODE
        AND H.SETID ='UCSHR'
        AND H.EFF_STATUS = 'A'
        AND H.EFFDT =
        (SELECT MAX(H_ED.EFFDT)
        FROM stable.PS_JOBCODE_TBL H_ED
        WHERE H.SETID = H_ED.SETID
            AND H.JOBCODE = H_ED.JOBCODE
            AND H_ED.EFF_STATUS = 'A'
            AND H_ED.EFFDT <= POSN.EFFDT
            AND H_ED.DML_IND <> 'D')
        AND H.DML_IND <> 'D'
    LEFT OUTER JOIN RPT.DEPARTMENT_HIERARCHY	DEPT_VC
    ON POSN.DEPTID = DEPT_VC.DEPTID
WHERE POSN.EFF_STATUS  = 'A'
    AND POSN.BUSINESS_UNIT in ('SDCMP','SDMED')
    AND POSN.DML_IND <> 'D'
    AND POSN.EFFDT         =
  (SELECT MAX(POSN1.EFFDT)
    FROM STABLE.PS_POSITION_DATA POSN1
    WHERE POSN1.POSITION_NBR  = POSN.POSITION_NBR
        -- AND POSN1.BUSINESS_UNIT = POSN.BUSINESS_UNIT
        AND POSN1.EFFDT <= getdate() --AND POSN1.EFF_STATUS  = 'A' 
        AND POSN1.DML_IND <> 'D'   
  )