SELECT deptid, *
FROM STABLE.PS_POSITION_DATA POSN1
WHERE 
POSITION_NBR = '40706162'
order by EFFDT desc
;

SELECT
    F.POSITION_NBR,
    F.DEPTID,
    F.ERNCD,
    F.FISCAL_YEAR,
    F.EFFDT,
    F.EFFSEQ,
    F.BUDGET_SEQ,
    F.DIST_PCT,
    F.ACCT_CD,
    F.DML_IND,
    F.FUNDING_END_DT,
    F.SETID,
    'Raw Data' AS Filter_Step
FROM STABLE.PS_DEPT_BUDGET_ERN F
WHERE F.POSITION_NBR = '40695542'
ORDER BY F.FISCAL_YEAR DESC, F.EFFDT DESC, F.EFFSEQ DESC, F.BUDGET_SEQ DESC;
