SELECT
    BC.POSITION_NBR,
    BC.COMMENT,
    CASE 
        WHEN H.POSITION_NBR_To_Check IS NOT NULL THEN 'MATCH: POSITION_NBR_To_Check'
        WHEN H.MANAGER_POSITION_NBR IS NOT NULL THEN 'MATCH: MANAGER_POSITION_NBR'
        WHEN H.MANAGER_POSITION_NBR_L1 IS NOT NULL THEN 'MATCH: MANAGER_POSITION_NBR_L1'
        WHEN H.MANAGER_POSITION_NBR_L2 IS NOT NULL THEN 'MATCH: MANAGER_POSITION_NBR_L2'
        WHEN H.MANAGER_POSITION_NBR_L3 IS NOT NULL THEN 'MATCH: MANAGER_POSITION_NBR_L3'
        WHEN H.MANAGER_POSITION_NBR_L4 IS NOT NULL THEN 'MATCH: MANAGER_POSITION_NBR_L4'
        ELSE 'NO MATCH'
    END AS Match_Status
FROM health_ods.[Health_ODS].[RPT].[TDS_UCPATH_POSITION_BROKEN_CHAIN] BC
    LEFT JOIN [stage].[UKG_EMPL_Inactive_Manager_Hierarchy] H
    ON BC.POSITION_NBR = H.POSITION_NBR_To_Check
        OR BC.POSITION_NBR = H.MANAGER_POSITION_NBR
        OR BC.POSITION_NBR = H.MANAGER_POSITION_NBR_L1
        OR BC.POSITION_NBR = H.MANAGER_POSITION_NBR_L2
        OR BC.POSITION_NBR = H.MANAGER_POSITION_NBR_L3
        OR BC.POSITION_NBR = H.MANAGER_POSITION_NBR_L4
ORDER BY Match_Status, BC.POSITION_NBR