-- Check if employee has business structure data
-- replaced single EMPLID variable with a set of EMPLIDs to check
DECLARE @EMPS TABLE (EMPLID VARCHAR(11));
INSERT INTO @EMPS
    (EMPLID)
VALUES
    ('10861356'),
    ('10856916'),
    ('10856229');

SELECT
    EMPL.EMPLID,
    FIN.POSITION_NBR,
    FIN.POSN_STATUS,
    FIN.FDM_COMBO_CD AS FIN_COMBOCODE,
    UKG_BS.COMBOCODE AS HTS_COMBOCODE,
    CASE
        WHEN FIN.FDM_COMBO_CD IS NULL AND UKG_BS.COMBOCODE IS NULL THEN 'BOTH_NULL'
        WHEN FIN.FDM_COMBO_CD = UKG_BS.COMBOCODE THEN 'MATCH'
        WHEN FIN.FDM_COMBO_CD IS NULL THEN 'FIN_NULL'
        WHEN UKG_BS.COMBOCODE IS NULL THEN 'HTS_NULL'
        ELSE 'MISMATCH'
    END AS COMBO_MATCH,
    CASE WHEN FIN.FDM_COMBO_CD = UKG_BS.COMBOCODE THEN 1 ELSE 0 END AS IS_MATCH,
    UKG_BS.Organization,
    UKG_BS.EntityTitle,
    UKG_BS.ServiceLineTitle,
    UKG_BS.FinancialUnit,
    UKG_BS.FundGroup
FROM health_ods.[health_ods].[RPT].CURRENT_EMPL_DATA EMPL
    INNER JOIN @EMPS E ON EMPL.EMPLID = E.EMPLID
    LEFT OUTER JOIN health_ods.[Health_ODS].[stage].[CURRENT_POSITION_PRI_FIN_UNIT_ALL_LOOKUP_V] FIN
    ON EMPL.POSITION_NBR = FIN.POSITION_NBR
    LEFT OUTER JOIN [hts].[UKG_BusinessStructure] UKG_BS
    ON UKG_BS.COMBOCODE = FIN.FDM_COMBO_CD
ORDER BY COMBO_MATCH DESC, FIN.POSITION_NBR;

-- -- Summary counts per EMPLID
-- SELECT
--     EMPL.EMPLID,
--     SUM(CASE WHEN FIN.FDM_COMBO_CD = UKG_BS.COMBOCODE THEN 1 ELSE 0 END) AS matches,
--     SUM(CASE WHEN FIN.FDM_COMBO_CD IS NULL AND UKG_BS.COMBOCODE IS NULL THEN 1 ELSE 0 END) AS both_null,
--     SUM(CASE WHEN FIN.FDM_COMBO_CD IS NULL AND UKG_BS.COMBOCODE IS NOT NULL THEN 1 ELSE 0 END) AS fin_null_hts_not_null,
--     SUM(CASE WHEN FIN.FDM_COMBO_CD IS NOT NULL AND UKG_BS.COMBOCODE IS NULL THEN 1 ELSE 0 END) AS hts_null_fin_not_null,
--     SUM(CASE WHEN FIN.FDM_COMBO_CD IS NOT NULL AND UKG_BS.COMBOCODE IS NOT NULL AND FIN.FDM_COMBO_CD <> UKG_BS.COMBOCODE THEN 1 ELSE 0 END) AS mismatches
-- FROM health_ods.[health_ods].[RPT].CURRENT_EMPL_DATA EMPL
--     INNER JOIN @EMPS E ON EMPL.EMPLID = E.EMPLID
--     LEFT OUTER JOIN health_ods.[Health_ODS].[stage].[CURRENT_POSITION_PRI_FIN_UNIT_ALL_LOOKUP_V] FIN
--         ON EMPL.POSITION_NBR = FIN.POSITION_NBR
--     LEFT OUTER JOIN [hts].[UKG_BusinessStructure] UKG_BS
--         ON UKG_BS.COMBOCODE = FIN.FDM_COMBO_CD
-- GROUP BY EMPL.EMPLID
-- ORDER BY EMPL.EMPLID;