MERGE [stage].[NON_UKG_MANAGER_LOG] AS Target
USING (
    SELECT Distinct
    [Person Number]
        , [First Name]
        , [Last Name]
        , [Middle Initial/Name]
        , [Short Name]
        , [Badge Number]
        , [Hire Date]
        , [Birth Date]
        , [Seniority Date]
        , [Manager Flag]
        , [Phone 1]
        , [Phone 2]
        , '' as [Email]  --make email blank until ready for testing
        , [Address]
        , [City]
        , [State]
        , [Postal Code]
        , [Country]
        , [Time Zone]
        , [Employment Status]
        , [Employment Status Effective Date]
        , [Reports to Manager]
        , [Union Code]
        , [Employee Type]
        , [Employee Classification]
        , [Pay Frequency]
        , [Worker Type]
        , [FTE %]
        , [FTE Standard Hours]
        , [FTE Full Time Hours]
        , [Standard Hours - Daily]
        , [Standard Hours - Weekly]
        , [Standard Hours - Pay Period]
        , [Base Wage Rate]
        , [Base Wage Rate Effective Date]
        , [User Account Name]
        , [User Account Status]
        , [User Password]
        , [Home Business Structure Level 1 - Organization]
        , [Home Business Structure Level 2 - Entity]
        , [Home Business Structure Level 3 - Service Line]
        , [Home Business Structure Level 4 - Financial Unit]
        , [Home Business Structure Level 5 - Fund Group]
        , [Home Business Structure Level 6]
        , [Home Business Structure Level 7]
        , [Home Business Structure Level 8]
        , [Home Business Structure Level 9]
        , [Home/Primary Job]
        , [Home Labor Category Level 1]
        , [Home Labor Category Level 2]
        , [Home Labor Category Level 3]
        , [Home Labor Category Level 4]
        , [Home Labor Category Level 5]
        , [Home Labor Category Level 6]
        , [Home Job and Labor Category Effective Date]
        , [Custom Field 1]
        , [Custom Field 2]
        , [Custom Field 3]
        , [Custom Field 4]
        , [Custom Field 5]
        , [Custom Field 6]
        , [Custom Field 7]
        , [Custom Field 8]
        , [Custom Field 9]
        , [Custom Field 10]
        , [Custom Date 1] -- re-order after [Custom Field 10]
        , [Custom Date 2]
        , [Custom Date 3]
        , [Custom Date 4]
        , [Custom Date 5]
        , [Custom Field 11]
        , [Custom Field 12]
        , [Custom Field 13]
        , [Custom Field 14]
        , [Custom Field 15]
        , [Custom Field 16]
        , [Custom Field 17]
        , [Custom Field 18]
        , [Custom Field 19]
        , [Custom Field 20]
        , [Custom Field 21]
        , [Custom Field 22]
        , [Custom Field 23]
        , [Custom Field 24]
        , [Custom Field 25]
        , [Custom Field 26]
        , [Custom Field 27]
        , [Custom Field 28]
        , [Custom Field 29]
        , [Custom Field 30]
        , [Additional Fields for CRT lookups]
FROM dbo.[UKG_EMPLOYEE_DATA]
WHERE [NON_UKG_MANAGER_FLAG]='T'
) AS Source
ON Target.[Person Number] = Source.[Person Number]
    AND Target.[Manager Flag] = Source.[Manager Flag]
WHEN NOT MATCHED BY TARGET THEN
    INSERT (
        [Person Number]
        ,[First Name]
        ,[Last Name]
        ,[Middle Initial/Name]
        ,[Short Name]
        ,[Badge Number]
        ,[Hire Date]
        ,[Birth Date]
        ,[Seniority Date]
        ,[Manager Flag]
        ,[Phone 1]
        ,[Phone 2]
        ,[Email]
        ,[Address]
        ,[City]
        ,[State]
        ,[Postal Code]
        ,[Country]
        ,[Time Zone]
        ,[Employment Status]
        ,[Employment Status Effective Date]
        ,[Reports to Manager]
        ,[Union Code]
        ,[Employee Type]
        ,[Employee Classification]
        ,[Pay Frequency]
        ,[Worker Type]
        ,[FTE %]
        ,[FTE Standard Hours]
        ,[FTE Full Time Hours]
        ,[Standard Hours - Daily]
        ,[Standard Hours - Weekly]
        ,[Standard Hours - Pay Period]
        ,[Base Wage Rate]
        ,[Base Wage Rate Effective Date]
        ,[User Account Name]
        ,[User Account Status]
        ,[User Password]
        ,[Home Business Structure Level 1 - Organization]
        ,[Home Business Structure Level 2 - Entity]
        ,[Home Business Structure Level 3 - Service Line]
        ,[Home Business Structure Level 4 - Financial Unit]
        ,[Home Business Structure Level 5 - Fund Group]
        ,[Home Business Structure Level 6]
        ,[Home Business Structure Level 7]
        ,[Home Business Structure Level 8]
        ,[Home Business Structure Level 9]
        ,[Home/Primary Job]
        ,[Home Labor Category Level 1]
        ,[Home Labor Category Level 2]
        ,[Home Labor Category Level 3]
        ,[Home Labor Category Level 4]
        ,[Home Labor Category Level 5]
        ,[Home Labor Category Level 6]
        ,[Home Job and Labor Category Effective Date]
        ,[Custom Field 1]
        ,[Custom Field 2]
        ,[Custom Field 3]
        ,[Custom Field 4]
        ,[Custom Field 5]
        ,[Custom Field 6]
        ,[Custom Field 7]
        ,[Custom Field 8]
        ,[Custom Field 9]
        ,[Custom Field 10]
        ,[Custom Date 1]
        ,[Custom Date 2]
        ,[Custom Date 3]
        ,[Custom Date 4]
        ,[Custom Date 5]
        ,[Custom Field 11]
        ,[Custom Field 12]
        ,[Custom Field 13]
        ,[Custom Field 14]
        ,[Custom Field 15]
        ,[Custom Field 16]
        ,[Custom Field 17]
        ,[Custom Field 18]
        ,[Custom Field 19]
        ,[Custom Field 20]
        ,[Custom Field 21]
        ,[Custom Field 22]
        ,[Custom Field 23]
        ,[Custom Field 24]
        ,[Custom Field 25]
        ,[Custom Field 26]
        ,[Custom Field 27]
        ,[Custom Field 28]
        ,[Custom Field 29]
        ,[Custom Field 30]
        ,[Additional Fields for CRT lookups]
    )
    VALUES (
        Source.[Person Number]
        ,Source.[First Name]
        ,Source.[Last Name]
        ,Source.[Middle Initial/Name]
        ,Source.[Short Name]
        ,Source.[Badge Number]
        ,Source.[Hire Date]
        ,Source.[Birth Date]
        ,Source.[Seniority Date]
        ,Source.[Manager Flag]
        ,Source.[Phone 1]
        ,Source.[Phone 2]
        ,Source.[Email]
        ,Source.[Address]
        ,Source.[City]
        ,Source.[State]
        ,Source.[Postal Code]
        ,Source.[Country]
        ,Source.[Time Zone]
        ,Source.[Employment Status]
        ,Source.[Employment Status Effective Date]
        ,Source.[Reports to Manager]
        ,Source.[Union Code]
        ,Source.[Employee Type]
        ,Source.[Employee Classification]
        ,Source.[Pay Frequency]
        ,Source.[Worker Type]
        ,Source.[FTE %]
        ,Source.[FTE Standard Hours]
        ,Source.[FTE Full Time Hours]
        ,Source.[Standard Hours - Daily]
        ,Source.[Standard Hours - Weekly]
        ,Source.[Standard Hours - Pay Period]
        ,Source.[Base Wage Rate]
        ,Source.[Base Wage Rate Effective Date]
        ,Source.[User Account Name]
        ,Source.[User Account Status]
        ,Source.[User Password]
        ,Source.[Home Business Structure Level 1 - Organization]
        ,Source.[Home Business Structure Level 2 - Entity]
        ,Source.[Home Business Structure Level 3 - Service Line]
        ,Source.[Home Business Structure Level 4 - Financial Unit]
        ,Source.[Home Business Structure Level 5 - Fund Group]
        ,Source.[Home Business Structure Level 6]
        ,Source.[Home Business Structure Level 7]
        ,Source.[Home Business Structure Level 8]
        ,Source.[Home Business Structure Level 9]
        ,Source.[Home/Primary Job]
        ,Source.[Home Labor Category Level 1]
        ,Source.[Home Labor Category Level 2]
        ,Source.[Home Labor Category Level 3]
        ,Source.[Home Labor Category Level 4]
        ,Source.[Home Labor Category Level 5]
        ,Source.[Home Labor Category Level 6]
        ,Source.[Home Job and Labor Category Effective Date]
        ,Source.[Custom Field 1]
        ,Source.[Custom Field 2]
        ,Source.[Custom Field 3]
        ,Source.[Custom Field 4]
        ,Source.[Custom Field 5]
        ,Source.[Custom Field 6]
        ,Source.[Custom Field 7]
        ,Source.[Custom Field 8]
        ,Source.[Custom Field 9]
        ,Source.[Custom Field 10]
        ,Source.[Custom Date 1]
        ,Source.[Custom Date 2]
        ,Source.[Custom Date 3]
        ,Source.[Custom Date 4]
        ,Source.[Custom Date 5]
        ,Source.[Custom Field 11]
        ,Source.[Custom Field 12]
        ,Source.[Custom Field 13]
        ,Source.[Custom Field 14]
        ,Source.[Custom Field 15]
        ,Source.[Custom Field 16]
        ,Source.[Custom Field 17]
        ,Source.[Custom Field 18]
        ,Source.[Custom Field 19]
        ,Source.[Custom Field 20]
        ,Source.[Custom Field 21]
        ,Source.[Custom Field 22]
        ,Source.[Custom Field 23]
        ,Source.[Custom Field 24]
        ,Source.[Custom Field 25]
        ,Source.[Custom Field 26]
        ,Source.[Custom Field 27]
        ,Source.[Custom Field 28]
        ,Source.[Custom Field 29]
        ,Source.[Custom Field 30]
        ,Source.[Additional Fields for CRT lookups]
    );