SELECT
    empl.emplid, empl.HR_STATUS, HPOSN.LEVEL
FROM health_ods.[RPT].[CURRENT_EMPL_DATA] EMPL
    JOIN health_ods.[health_ods].[RPT].ORG_HIERARCHY_POSN	  HPOSN
    ON HPOSN.EMPLID = EMPL.EMPLID
        AND HPOSN.EMPL_RCD	= EMPL.EMPL_RCD
WHERE 
HPOSN.LEVEL='LEVEL5'
GO
