SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM HealthTime.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'SAL_ADMIN_PLAN'
ORDER BY TABLE_SCHEMA, TABLE_NAME;