DROP TABLE IF EXISTS STAGE.UKG_EMPL_HRATE_EFFDT_T_TEMP;
SELECT H.EMPLID,
    H.HOURLY_RT,
    H.EFFDT ,
    H.UPD_BT_DTM ,
    H.SAL_ADMIN_PLAN,
    ROW_NUMBER() OVER (
            PARTITION BY H.EMPLID 
            ORDER BY H.EFFDT ASC, UPD_BT_DTM DESC ) AS RN
INTO  STAGE.UKG_EMPL_HRATE_EFFDT_T_TEMP
FROM health_ods.[health_ods].[stable].PS_JOB H, STAGE.UKG_EMPL_T  L
WHERE H.EMPLID = L.EMPLID
    AND H.EMPL_RCD = L.EMPL_RCD
    AND H.HOURLY_RT = L.HOURLY_RT
    AND H.JOB_INDICATOR = 'P'
    AND H.DML_IND <> 'D'
    and (H.SAL_ADMIN_PLAN <> 'BYA') -- 08/22/2025
    and H.emplid=10423463