USE [HealthTime]
GO

CREATE TABLE [dbo].[NON_UKG_MANAGER_HISTORY](
	[DEPTID] [varchar](10) NULL,
	[VC_CODE] [varchar](50) NULL,
	[FDM_COMBO_CD] [varchar](25) NULL,
	[COMBOCODE] [varchar](9) NULL,
	[REPORTS_TO] [varchar](8) NULL,
	[MANAGER_EMPLID] [varchar](11) NULL,
	[NON_UKG_MANAGER_FLAG] [varchar](1) NOT NULL,
	[position_nbr] [varchar](8) NULL,
	[EMPLID] [varchar](11) NULL,
	[EMPL_RCD] [smallint] NULL,
	[jobcode] [varchar](6) NULL,
	[POSITION_DESCR] [varchar](30) NULL,
	[hr_status] [varchar](1) NULL,
	[FTE_SUM] [numeric](38, 6) NULL,
	[fte] [numeric](7, 6) NULL,
	[empl_Status] [varchar](1) NULL,
	[JobGroup] [varchar](50) NULL,
	[FundGroup] [varchar](10) NULL,
	[Person Number] [varchar](11) NOT NULL,
	[First Name] [varchar](30) NULL,
	[Last Name] [varchar](30) NOT NULL,
	[Middle Initial/Name] [varchar](1) NULL,
	[Short Name] [varchar](1) NOT NULL,
	[Badge Number] [varchar](1) NOT NULL,
	[Hire Date] [varchar](30) NOT NULL,
	[Birth Date] [varchar](1) NOT NULL,
	[Seniority Date] [varchar](1) NOT NULL,
	[Manager Flag] [varchar](1) NOT NULL,
	[Phone 1] [varchar](8000) NULL,
	[Phone 2] [varchar](8000) NULL,
	[Email] [varchar](8000) NULL,
	[Address] [varchar](1) NOT NULL,
	[City] [varchar](1) NOT NULL,
	[State] [varchar](1) NOT NULL,
	[Postal Code] [varchar](1) NOT NULL,
	[Country] [varchar](1) NOT NULL,
	[Time Zone] [varchar](7) NOT NULL,
	[Employment Status] [varchar](1) NOT NULL,
	[Employment Status Effective Date] [varchar](30) NOT NULL,
	[Reports to Manager] [varchar](11) NULL,
	[Union Code] [varchar](3) NULL,
	[Employee Type] [varchar](1) NULL,
	[Employee Classification] [varchar](1) NULL,
	[Pay Frequency] [varchar](5) NULL,
	[Worker Type] [varchar](3) NULL,
	[FTE %] [varchar](30) NULL,
	[FTE Standard Hours] [varchar](1) NOT NULL,
	[FTE Full Time Hours] [varchar](1) NOT NULL,
	[Standard Hours - Daily] [varchar](1) NOT NULL,
	[Standard Hours - Weekly] [varchar](1) NOT NULL,
	[Standard Hours - Pay Period] [varchar](1) NOT NULL,
	[Base Wage Rate] [varchar](30) NULL,
	[Base Wage Rate Effective Date] [varchar](30) NOT NULL,
	[User Account Name] [varchar](11) NULL,
	[User Account Status] [varchar](1) NOT NULL,
	[User Password] [varchar](1) NOT NULL,
	[Home Business Structure Level 1 - Organization] [varchar](50) NOT NULL,
	[Home Business Structure Level 2 - Entity] [varchar](250) NOT NULL,
	[Home Business Structure Level 3 - Service Line] [varchar](250) NOT NULL,
	[Home Business Structure Level 4 - Financial Unit] [varchar](10) NOT NULL,
	[Home Business Structure Level 5 - Fund Group] [varchar](10) NOT NULL,
	[Home Business Structure Level 6] [varchar](1) NOT NULL,
	[Home Business Structure Level 7] [varchar](1) NOT NULL,
	[Home Business Structure Level 8] [varchar](1) NOT NULL,
	[Home Business Structure Level 9] [varchar](1) NOT NULL,
	[Home/Primary Job] [varchar](50) NOT NULL,
	[Home Labor Category Level 1] [varchar](39) NOT NULL,
	[Home Labor Category Level 2] [varchar](6) NOT NULL,
	[Home Labor Category Level 3] [varchar](1) NOT NULL,
	[Home Labor Category Level 4] [varchar](1) NOT NULL,
	[Home Labor Category Level 5] [varchar](1) NOT NULL,
	[Home Labor Category Level 6] [varchar](1) NOT NULL,
	[Home Job and Labor Category Effective Date] [varchar](30) NOT NULL,
	[Custom Field 1] [varchar](10) NULL,
	[Custom Field 2] [varchar](3) NULL,
	[Custom Field 3] [varchar](1) NOT NULL,
	[Custom Field 4] [varchar](3) NULL,
	[Custom Field 5] [varchar](1) NOT NULL,
	[Custom Field 6] [varchar](1) NOT NULL,
	[Custom Field 7] [varchar](5) NULL,
	[Custom Field 8] [varchar](1) NOT NULL,
	[Custom Field 9] [varchar](1) NOT NULL,
	[Custom Field 10] [varchar](3) NULL,
	[Custom Date 1] [varchar](30) NULL,
	[Custom Date 2] [varchar](30) NOT NULL,
	[Custom Date 3] [varchar](1) NOT NULL,
	[Custom Date 4] [varchar](30) NOT NULL,
	[Custom Date 5] [varchar](1) NOT NULL,
	[Custom Field 11] [varchar](1) NOT NULL,
	[Custom Field 12] [varchar](1) NOT NULL,
	[Custom Field 13] [varchar](1) NOT NULL,
	[Custom Field 14] [varchar](30) NULL,
	[Custom Field 15] [varchar](30) NULL,
	[Custom Field 16] [varchar](1) NOT NULL,
	[Custom Field 17] [varchar](50) NULL,
	[Custom Field 18] [varchar](1) NOT NULL,
	[Custom Field 19] [varchar](1) NOT NULL,
	[Custom Field 20] [varchar](1) NOT NULL,
	[Custom Field 21] [varchar](1) NOT NULL,
	[Custom Field 22] [varchar](1) NOT NULL,
	[Custom Field 23] [varchar](1) NOT NULL,
	[Custom Field 24] [varchar](1) NOT NULL,
	[Custom Field 25] [varchar](1) NOT NULL,
	[Custom Field 26] [varchar](1) NOT NULL,
	[Custom Field 27] [varchar](1) NOT NULL,
	[Custom Field 28] [varchar](1) NOT NULL,
	[Custom Field 29] [varchar](1) NOT NULL,
	[Custom Field 30] [varchar](1) NOT NULL,
	[Additional Fields for CRT lookups] [varchar](1) NOT NULL,
	[termination_dt] [date] NULL,
	[action] [varchar](3) NULL,
	[action_dt] [date] NULL,
	[hash_value] [varbinary](16) NOT NULL,
	[NOTE] [varchar](255) NULL,
	[snapshot_date] [date] NOT NULL,
	Update_DT [date] NULL
) ON [PRIMARY]
GO


