-- Check if employee has business structure data
-- build @EMPS from employee temp table where FIN combo exists but no HTS mapping
DECLARE @EMPS TABLE (EMPLID VARCHAR(11));

INSERT INTO @EMPS
    (EMPLID)
SELECT DISTINCT
    EMPL.EMPLID
FROM [dbo].[UKG_EMPLOYEE_DATA] EMPL
    LEFT JOIN health_ods.[Health_ODS].[stage].[CURRENT_POSITION_PRI_FIN_UNIT_ALL_LOOKUP_V] FIN
    ON EMPL.POSITION_NBR = FIN.POSITION_NBR
    LEFT JOIN [hts].[UKG_BusinessStructure] UKG_BS
    ON UKG_BS.COMBOCODE = FIN.FDM_COMBO_CD
WHERE FIN.FDM_COMBO_CD IS NOT NULL
    AND UKG_BS.COMBOCODE IS NULL
    and empl.emplid=10416615
    and FIN.POSN_SEQ=1;

-- build temp-table of deduped rows
IF OBJECT_ID('tempdb..#cte') IS NOT NULL DROP TABLE #cte;

SELECT
    EMPL.EMPLID,
    FIN.POSITION_NBR,
    FIN.POSN_STATUS,
    FIN.FDM_COMBO_CD AS FIN_COMBOCODE,
    UKG_BS.COMBOCODE AS HTS_COMBOCODE,
    CASE
        WHEN FIN.FDM_COMBO_CD IS NULL AND UKG_BS.COMBOCODE IS NULL THEN 'BOTH_NULL'
        WHEN FIN.FDM_COMBO_CD = UKG_BS.COMBOCODE THEN 'MATCH'
        WHEN FIN.FDM_COMBO_CD IS NULL THEN 'FIN_NULL'
        WHEN UKG_BS.COMBOCODE IS NULL THEN 'HTS_NULL'
        ELSE 'MISMATCH'
    END AS COMBO_MATCH,
    CASE WHEN FIN.FDM_COMBO_CD = UKG_BS.COMBOCODE THEN 1 ELSE 0 END AS IS_MATCH,
    UKG_BS.Organization,
    UKG_BS.EntityTitle,
    UKG_BS.ServiceLineTitle,
    UKG_BS.FinancialUnit,
    UKG_BS.FundGroup,
    ROW_NUMBER() OVER (
        PARTITION BY EMPL.EMPLID, FIN.POSITION_NBR
        ORDER BY (CASE WHEN FIN.FDM_COMBO_CD IS NOT NULL THEN 0 ELSE 1 END), FIN.FDM_COMBO_CD DESC
    ) AS rn
INTO #cte
FROM health_ods.[health_ods].[RPT].CURRENT_EMPL_DATA EMPL
    INNER JOIN @EMPS E ON EMPL.EMPLID = E.EMPLID
    LEFT OUTER JOIN health_ods.[Health_ODS].[stage].[CURRENT_POSITION_PRI_FIN_UNIT_ALL_LOOKUP_V] FIN
    ON EMPL.POSITION_NBR = FIN.POSITION_NBR
    LEFT OUTER JOIN [hts].[UKG_BusinessStructure] UKG_BS
    ON UKG_BS.COMBOCODE = FIN.FDM_COMBO_CD
        and EMPL.hr_status='A'
        and EMPL.JOB_INDICATOR='P'
        and FIN.POSN_SEQ=1
        and empl.emplid=10416615
;

-- Detailed: top 1 row per EMPLID+POSITION_NBR where HTS mapping is missing
SELECT
    EMPLID,
    POSITION_NBR,
    POSN_STATUS,
    FIN_COMBOCODE,
    HTS_COMBOCODE,
    COMBO_MATCH,
    IS_MATCH,
    Organization,
    EntityTitle,
    ServiceLineTitle,
    FinancialUnit,
    FundGroup
FROM #cte
WHERE rn = 1
    AND HTS_COMBOCODE IS NULL
ORDER BY COMBO_MATCH DESC, POSITION_NBR;

-- Summary counts per EMPLID using deduped rows
SELECT
    EMPLID,
    SUM(CASE WHEN FIN_COMBOCODE = HTS_COMBOCODE THEN 1 ELSE 0 END) AS matches,
    SUM(CASE WHEN FIN_COMBOCODE IS NULL AND HTS_COMBOCODE IS NULL THEN 1 ELSE 0 END) AS both_null,
    SUM(CASE WHEN FIN_COMBOCODE IS NULL AND HTS_COMBOCODE IS NOT NULL THEN 1 ELSE 0 END) AS fin_null_hts_not_null,
    SUM(CASE WHEN FIN_COMBOCODE IS NOT NULL AND HTS_COMBOCODE IS NULL THEN 1 ELSE 0 END) AS hts_null_fin_not_null,
    SUM(CASE WHEN FIN_COMBOCODE IS NOT NULL AND HTS_COMBOCODE IS NOT NULL AND FIN_COMBOCODE <> HTS_COMBOCODE THEN 1 ELSE 0 END) AS mismatches
FROM #cte
WHERE rn = 1
GROUP BY EMPLID
ORDER BY EMPLID;

IF OBJECT_ID('tempdb..#cte') IS NOT NULL DROP TABLE #cte;